# Step 1

In [16]:
MOVIES_PATH = "../data/data/movieLens_1M/movies.dat"
RATINGS_PATH = "../data/data/movieLens_1M/ratings.dat"
USER_PATH = "../data/data/movieLens_1M/users.dat"

In [6]:
import pandas as pd
import numpy as np

In [13]:
# Load in the datasets
movies_df = pd.read_csv(
    MOVIES_PATH, 
    sep="::", 
    header=None, 
    names=["MovieID", "Title", "Genres"], 
    engine="python",
    encoding="latin-1"
)

movies_df.head()

   MovieID                               Title                        Genres
0        1                    Toy Story (1995)   Animation|Children's|Comedy
1        2                      Jumanji (1995)  Adventure|Children's|Fantasy
2        3             Grumpier Old Men (1995)                Comedy|Romance
3        4            Waiting to Exhale (1995)                  Comedy|Drama
4        5  Father of the Bride Part II (1995)                        Comedy

In [15]:
ratings_df = pd.read_csv(
    RATINGS_PATH,
    sep="::",
    header=None,
    names=["UserID", "MovieID", "Rating", "Timestamp"],
    engine="python",
)

ratings_df.head()

   UserID  MovieID  Rating  Timestamp
0       1     1193       5  978300760
1       1      661       3  978302109
2       1      914       3  978301968
3       1     3408       4  978300275
4       1     2355       5  978824291

In [17]:
users_df = pd.read_csv(
    USER_PATH,
    sep="::",
    header=None,
    names=["UserID", "Gender", "Age", "Occupation", "Zip-code"],
    engine="python",
)

users_df.head()

   UserID Gender  Age  Occupation Zip-code
0       1      F    1          10    48067
1       2      M   56          16    70072
2       3      M   25          15    55117
3       4      M   45           7    02460
4       5      M   25          20    55455